on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10

name: Upload Release Assets

jobs:
  build:
    name: Upload Assets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.4.0
      - name: Install # This would actually build your project, using zip for an example artifact
        run: yarn --frozen-lockfile
      - name: Build Extension .vsix
        run: yarn run package-extension
      - run: zip code-spell-checker build/*
      - name: Upload Release Assets
        uses: alexellis/upload-assets@0.3.0
        with:
          asset_paths: '["code-spell-checker.zip"]'

# cspell:ignore vsix alexellis
